version: '3.5'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.12
    user: '101:101'
    container_name: clickhouse-server
    hostname: clickhouse-server
    volumes:
      - ./config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./data:/var/lib/clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    logging:
      driver: "json-file"
      options:
        max-file: 1
        max-size: 10m
    deploy:
      resources:
        limits:
          memory: 25Gb
