version: "3.7"

services:
  redis:
    image: redislabs/redisearch:2.10.7
    ports:
      - '6379:6379'
    logging:
      driver: "json-file"
      options:
        max-file: 1
        max-size: 10m
    volumes:
      - ./data:/data
    deploy:
      resources:
        limits:
          memory: 25Gb
