version: '3.5'

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    environment:
      ELASTIC_PASSWORD: "passwd"
      KIBANA_PASSWORD: "passwd"
      SERVER_SSL_ENABLED: "false"
      discovery.type: "single-node"
      xpack.security.enabled: "false"
      bootstrap.memory_lock: "true"
    healthcheck:
      test:
       [
         "CMD-SHELL",
         "curl -s -I http://localhost:9200",
       ]
      interval: 10s
      timeout: 10s
      retries: 120
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    logging:
      driver: "json-file"
      options:
        max-file: 1
        max-size: 10m
    deploy:
      resources:
        limits:
          memory: 25Gb

  kibana:
     depends_on:
       es:
         condition: service_healthy
     image: docker.elastic.co/kibana/kibana:8.10.2
     labels:
       co.elastic.logs/module: kibana
     ports:
      - "5601:5601"
     environment:
       - SERVERNAME=kibana
       - ELASTICSEARCH_HOSTS=http://es:9200
       - ELASTICSEARCH_USERNAME=kibana_system
       - ELASTICSEARCH_PASSWORD=passwd
     healthcheck:
       test:
         [
           "CMD-SHELL",
           "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
         ]
       interval: 10s
       timeout: 10s
       retries: 120